"""exam column mappings

Revision ID: 22c8055463af
Revises: 96090f180df2
Create Date: 2026-06-14 10:53:03.226450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22c8055463af'
down_revision: Union[str, Sequence[str], None] = '96090f180df2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_column_mappings',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('semester_id', sa.UUID(), nullable=False),
    sa.Column('score_category', postgresql.ENUM('ORAL', 'REGULAR', 'MIDTERM', 'FINAL', name='score_category_enum', create_type=False), nullable=False),
    sa.Column('column_index', sa.SmallInteger(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=True),
    sa.Column('grade_id', sa.UUID(), nullable=True),
    sa.Column('exam_paper_id', sa.UUID(), nullable=False),
    sa.Column('mapped_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(score_category = 'REGULAR' AND class_id IS NOT NULL AND grade_id IS NULL) OR (score_category IN ('MIDTERM','FINAL') AND grade_id IS NOT NULL AND class_id IS NULL)", name=op.f('ck_exam_column_mappings_mapping_scope_consistency')),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_exam_column_mappings_class_id_classes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exam_paper_id'], ['exam_papers.id'], name=op.f('fk_exam_column_mappings_exam_paper_id_exam_papers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], name=op.f('fk_exam_column_mappings_grade_id_grades'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mapped_by'], ['users.id'], name=op.f('fk_exam_column_mappings_mapped_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], name=op.f('fk_exam_column_mappings_semester_id_semesters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_exam_column_mappings_subject_id_subjects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_column_mappings')),
    sa.UniqueConstraint('subject_id', 'semester_id', 'score_category', 'column_index', 'class_id', 'grade_id', name='uq_exam_mapping', postgresql_nulls_not_distinct=True)
    )
    op.create_index('idx_mapping_class', 'exam_column_mappings', ['class_id'], unique=False)
    op.create_index('idx_mapping_exam', 'exam_column_mappings', ['exam_paper_id'], unique=False)
    op.create_index('idx_mapping_grade', 'exam_column_mappings', ['grade_id'], unique=False)
    op.create_index('idx_mapping_subject_sem', 'exam_column_mappings', ['subject_id', 'semester_id'], unique=False)
    op.alter_column('exam_papers', 'score_type',
               existing_type=postgresql.ENUM('TX1', 'TX2', 'TX3', 'TX4', 'GK', 'CK', name='score_type_enum'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exam_papers', 'score_type',
               existing_type=postgresql.ENUM('TX1', 'TX2', 'TX3', 'TX4', 'GK', 'CK', name='score_type_enum'),
               nullable=False)
    op.drop_index('idx_mapping_subject_sem', table_name='exam_column_mappings')
    op.drop_index('idx_mapping_grade', table_name='exam_column_mappings')
    op.drop_index('idx_mapping_exam', table_name='exam_column_mappings')
    op.drop_index('idx_mapping_class', table_name='exam_column_mappings')
    op.drop_table('exam_column_mappings')
    # ### end Alembic commands ###
