"""initial schema

Revision ID: 5b1094a3ac09
Revises: 
Create Date: 2026-06-12 01:28:23.670088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b1094a3ac09'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # --- Extensions ---
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # NOTE: enum types được Alembic tự tạo (mỗi type đúng một lần) khi tạo bảng đầu
    # tiên dùng tới chúng. DROP TYPE tương ứng nằm ở cuối downgrade().

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schools')),
    sa.UniqueConstraint('code', name=op.f('uq_schools_code'))
    )
    op.create_table('academic_years',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_academic_years_school_id_schools'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_academic_years')),
    sa.UniqueConstraint('school_id', 'name', name='uq_academic_year_school_name')
    )
    op.create_table('grades',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('grade_number', sa.SmallInteger(), nullable=False),
    sa.Column('school_level', sa.Enum('PRIMARY', 'SECONDARY', 'HIGH', 'ALL', name='school_level_enum', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('grade_number BETWEEN 1 AND 12', name=op.f('ck_grades_grade_number_valid')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_grades_school_id_schools'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grades')),
    sa.UniqueConstraint('school_id', 'grade_number', name='uq_grade_school_number')
    )
    op.create_table('students',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('student_code', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("gender IN ('MALE', 'FEMALE', 'OTHER')", name=op.f('ck_students_gender_valid')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_students_school_id_schools'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_students')),
    sa.UniqueConstraint('school_id', 'student_code', name='uq_student_school_code')
    )
    op.create_index('idx_students_name', 'students', ['full_name'], unique=False, postgresql_using='gin', postgresql_ops={'full_name': 'gin_trgm_ops'})
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'PRINCIPAL', 'GRADE_HEAD_PRIMARY', 'HOMEROOM_TEACHER_PRIMARY', 'SUBJECT_TEACHER', 'HOMEROOM_TEACHER_SECONDARY', 'SUBJECT_HEAD', name='user_role_enum', create_type=False), nullable=False),
    sa.Column('school_level', sa.Enum('PRIMARY', 'SECONDARY', 'HIGH', 'ALL', name='school_level_enum', create_type=False), server_default=sa.text("'ALL'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_users_school_id_schools'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_index('idx_users_school', 'users', ['school_id'], unique=False)
    op.create_table('ai_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('context_filter', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_sessions'))
    )
    op.create_index('idx_session_user', 'ai_sessions', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action IN ('INSERT', 'UPDATE', 'DELETE')", name=op.f('ck_audit_logs_action_valid')),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], name=op.f('fk_audit_logs_changed_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('idx_audit_table', 'audit_logs', ['table_name', 'record_id'], unique=False)
    op.create_index('idx_audit_time', 'audit_logs', ['changed_at'], unique=False)
    op.create_index('idx_audit_user', 'audit_logs', ['changed_by'], unique=False)
    op.create_table('classes',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('grade_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.Column('student_count', sa.SmallInteger(), server_default=sa.text('0'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], name=op.f('fk_classes_academic_year_id_academic_years')),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], name=op.f('fk_classes_grade_id_grades'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_classes')),
    sa.UniqueConstraint('grade_id', 'name', 'academic_year_id', name='uq_class_grade_name_year')
    )
    op.create_index('idx_classes_grade', 'classes', ['grade_id'], unique=False)
    op.create_index('idx_classes_year', 'classes', ['academic_year_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_table('report_schedules',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('filter_params', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('cron_expr', sa.String(length=100), nullable=False),
    sa.Column('recipients', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("report_type IN ('school_overview','grade','subject','class','at_risk')", name=op.f('ck_report_schedules_report_type_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_report_schedules_created_by_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_schedules'))
    )
    op.create_table('semesters',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('number', sa.SmallInteger(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.CheckConstraint('number IN (1, 2)', name=op.f('ck_semesters_number_valid')),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], name=op.f('fk_semesters_academic_year_id_academic_years'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_semesters')),
    sa.UniqueConstraint('academic_year_id', 'number', name='uq_semester_year_number')
    )
    op.create_table('subjects',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('applicable_level', sa.Enum('PRIMARY', 'SECONDARY', 'HIGH', 'ALL', name='school_level_enum', create_type=False), server_default=sa.text("'ALL'"), nullable=False),
    sa.Column('subject_head_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_subjects_school_id_schools'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_head_id'], ['users.id'], name=op.f('fk_subjects_subject_head_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subjects')),
    sa.UniqueConstraint('school_id', 'code', name='uq_subject_school_code')
    )
    op.create_table('ai_messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', name='ai_session_role_enum', create_type=False), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('generated_sql', sa.Text(), nullable=True),
    sa.Column('guardrail_status', sa.Enum('PASSED', 'BLOCKED_INJECTION', 'BLOCKED_SQL', 'BLOCKED_PII', 'BLOCKED_SENSITIVE', name='guardrail_status_enum', create_type=False), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['ai_sessions.id'], name=op.f('fk_ai_messages_session_id_ai_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_messages'))
    )
    op.create_index('idx_message_session', 'ai_messages', ['session_id'], unique=False)
    op.create_table('curriculum_units',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('grade_number', sa.SmallInteger(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('grade_number BETWEEN 1 AND 12', name=op.f('ck_curriculum_units_grade_number_valid')),
    sa.ForeignKeyConstraint(['parent_id'], ['curriculum_units.id'], name=op.f('fk_curriculum_units_parent_id_curriculum_units'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_curriculum_units_subject_id_subjects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_curriculum_units')),
    sa.UniqueConstraint('subject_id', 'grade_number', 'code', name='uq_curriculum_subject_grade_code')
    )
    op.create_index('idx_curri_parent', 'curriculum_units', ['parent_id'], unique=False)
    op.create_index('idx_curri_subject', 'curriculum_units', ['subject_id', 'grade_number'], unique=False)
    op.create_table('enrollments',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.Column('enrolled_at', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], name=op.f('fk_enrollments_academic_year_id_academic_years')),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_enrollments_class_id_classes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_enrollments_student_id_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enrollments')),
    sa.UniqueConstraint('student_id', 'academic_year_id', name='uq_enrollment_student_year')
    )
    op.create_index('idx_enroll_class', 'enrollments', ['class_id'], unique=False)
    op.create_index('idx_enroll_student', 'enrollments', ['student_id'], unique=False)
    op.create_index('idx_enroll_year', 'enrollments', ['academic_year_id'], unique=False)
    op.create_table('exam_papers',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('semester_id', sa.UUID(), nullable=False),
    sa.Column('grade_id', sa.UUID(), nullable=True),
    sa.Column('score_type', sa.Enum('TX1', 'TX2', 'TX3', 'TX4', 'GK', 'CK', name='score_type_enum', create_type=False), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('file_type', sa.Enum('PDF', 'WORD', 'IMAGE', 'OTHER', name='file_type_enum', create_type=False), server_default=sa.text("'PDF'"), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficulty_enum', create_type=False), nullable=True),
    sa.Column('difficulty_coefficient', sa.Numeric(precision=3, scale=2), server_default=sa.text('1.00'), nullable=False),
    sa.Column('num_questions', sa.SmallInteger(), nullable=True),
    sa.Column('total_points', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('topics', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('ai_analysis', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('difficulty_coefficient BETWEEN 0.50 AND 1.50', name=op.f('ck_exam_papers_difficulty_coefficient_range')),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], name=op.f('fk_exam_papers_grade_id_grades')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_exam_papers_school_id_schools'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], name=op.f('fk_exam_papers_semester_id_semesters'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_exam_papers_subject_id_subjects'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_exam_papers_uploaded_by_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_papers'))
    )
    op.create_index('idx_exam_grade', 'exam_papers', ['grade_id'], unique=False)
    op.create_index('idx_exam_semester', 'exam_papers', ['semester_id'], unique=False)
    op.create_index('idx_exam_subject', 'exam_papers', ['subject_id'], unique=False)
    op.create_index('idx_exam_type', 'exam_papers', ['score_type'], unique=False)
    op.create_table('teacher_assignments',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.Column('role_context', sa.Enum('HOMEROOM_PRIMARY', 'HOMEROOM_SECONDARY', 'SUBJECT_TEACHER', 'GRADE_HEAD', 'SUBJECT_HEAD', name='role_context_enum', create_type=False), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=True),
    sa.Column('grade_id', sa.UUID(), nullable=True),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n    (role_context = 'HOMEROOM_PRIMARY'   AND class_id IS NOT NULL AND subject_id IS NULL     AND grade_id IS NULL) OR\n    (role_context = 'GRADE_HEAD'         AND grade_id IS NOT NULL AND class_id IS NULL       AND subject_id IS NULL) OR\n    (role_context = 'SUBJECT_TEACHER'    AND class_id IS NOT NULL AND subject_id IS NOT NULL AND grade_id IS NULL) OR\n    (role_context = 'HOMEROOM_SECONDARY' AND class_id IS NOT NULL AND subject_id IS NULL     AND grade_id IS NULL) OR\n    (role_context = 'SUBJECT_HEAD'       AND subject_id IS NOT NULL AND class_id IS NULL     AND grade_id IS NULL)\n", name=op.f('ck_teacher_assignments_assignment_consistency')),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], name=op.f('fk_teacher_assignments_academic_year_id_academic_years'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_teacher_assignments_class_id_classes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], name=op.f('fk_teacher_assignments_grade_id_grades'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_teacher_assignments_subject_id_subjects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_teacher_assignments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teacher_assignments')),
    sa.UniqueConstraint('user_id', 'role_context', 'class_id', 'grade_id', 'subject_id', 'academic_year_id', name='uq_teacher_assignment', postgresql_nulls_not_distinct=True)
    )
    op.create_index('idx_ta_class', 'teacher_assignments', ['class_id'], unique=False)
    op.create_index('idx_ta_grade', 'teacher_assignments', ['grade_id'], unique=False)
    op.create_index('idx_ta_subject', 'teacher_assignments', ['subject_id'], unique=False)
    op.create_index('idx_ta_user', 'teacher_assignments', ['user_id'], unique=False)
    op.create_index('idx_ta_year', 'teacher_assignments', ['academic_year_id'], unique=False)
    op.create_table('exam_competencies',
    sa.Column('exam_paper_id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=4, scale=3), server_default=sa.text('0'), nullable=False),
    sa.Column('bloom_level', sa.SmallInteger(), nullable=True),
    sa.CheckConstraint('bloom_level BETWEEN 1 AND 6', name=op.f('ck_exam_competencies_bloom_level_range')),
    sa.CheckConstraint('weight BETWEEN 0 AND 1', name=op.f('ck_exam_competencies_weight_range')),
    sa.ForeignKeyConstraint(['exam_paper_id'], ['exam_papers.id'], name=op.f('fk_exam_competencies_exam_paper_id_exam_papers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['curriculum_units.id'], name=op.f('fk_exam_competencies_unit_id_curriculum_units'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('exam_paper_id', 'unit_id', name=op.f('pk_exam_competencies'))
    )
    op.create_index('idx_examcomp_unit', 'exam_competencies', ['unit_id'], unique=False)
    op.create_table('scores',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('semester_id', sa.UUID(), nullable=False),
    sa.Column('score_type', sa.Enum('TX1', 'TX2', 'TX3', 'TX4', 'GK', 'CK', name='score_type_enum', create_type=False), nullable=False),
    sa.Column('value', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('exam_paper_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', name='score_status_enum', create_type=False), server_default=sa.text("'DRAFT'"), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('entered_by', sa.UUID(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('value >= 0 AND value <= 10', name=op.f('ck_scores_value_range')),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_scores_approved_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_scores_class_id_classes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['entered_by'], ['users.id'], name=op.f('fk_scores_entered_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['exam_paper_id'], ['exam_papers.id'], name=op.f('fk_scores_exam_paper_id_exam_papers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], name=op.f('fk_scores_semester_id_semesters'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_scores_student_id_students'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_scores_subject_id_subjects'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scores')),
    sa.UniqueConstraint('student_id', 'subject_id', 'semester_id', 'score_type', name='uq_score_unique')
    )
    op.create_index('idx_scores_class', 'scores', ['class_id'], unique=False)
    op.create_index('idx_scores_compound', 'scores', ['subject_id', 'semester_id', 'score_type'], unique=False)
    op.create_index('idx_scores_exam', 'scores', ['exam_paper_id'], unique=False)
    op.create_index('idx_scores_semester', 'scores', ['semester_id'], unique=False)
    op.create_index('idx_scores_status', 'scores', ['status'], unique=False)
    op.create_index('idx_scores_student', 'scores', ['student_id'], unique=False)
    op.create_index('idx_scores_subject', 'scores', ['subject_id'], unique=False)
    op.create_index('idx_scores_type', 'scores', ['score_type'], unique=False)
    # ### end Alembic commands ###

    # --- Trigger: updated_at auto-update ---
    op.execute(
        """
        CREATE OR REPLACE FUNCTION update_updated_at()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = NOW();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    for tbl in ("users", "schools", "students", "scores", "exam_papers", "ai_sessions"):
        op.execute(
            f"CREATE TRIGGER trg_{tbl}_updated BEFORE UPDATE ON {tbl} "
            "FOR EACH ROW EXECUTE FUNCTION update_updated_at()"
        )

    # --- Trigger: audit log cho scores (app phải SET LOCAL app.current_user_id) ---
    op.execute(
        """
        CREATE OR REPLACE FUNCTION audit_scores_change()
        RETURNS TRIGGER AS $$
        DECLARE
            v_user UUID := NULLIF(current_setting('app.current_user_id', true), '')::uuid;
        BEGIN
            IF TG_OP = 'UPDATE' THEN
                INSERT INTO audit_logs(table_name, record_id, action, changed_by, old_values, new_values)
                VALUES ('scores', OLD.id, 'UPDATE', v_user, to_jsonb(OLD), to_jsonb(NEW));
                RETURN NEW;
            ELSIF TG_OP = 'DELETE' THEN
                INSERT INTO audit_logs(table_name, record_id, action, changed_by, old_values)
                VALUES ('scores', OLD.id, 'DELETE', v_user, to_jsonb(OLD));
                RETURN OLD;
            END IF;
            RETURN NULL;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        "CREATE TRIGGER trg_audit_scores AFTER UPDATE OR DELETE ON scores "
        "FOR EACH ROW EXECUTE FUNCTION audit_scores_change()"
    )

    # --- Function: ĐTB môn học kỳ theo Thông tư 22/2020 ---
    op.execute(
        """
        CREATE OR REPLACE FUNCTION calc_subject_average(
            p_student_id UUID, p_subject_id UUID, p_semester_id UUID
        ) RETURNS NUMERIC(4,2) AS $$
        DECLARE
            v_tx_sum   NUMERIC := 0;
            v_tx_count INT     := 0;
            v_gk       NUMERIC;
            v_ck       NUMERIC;
        BEGIN
            SELECT COALESCE(SUM(value), 0), COUNT(*) INTO v_tx_sum, v_tx_count
              FROM scores
             WHERE student_id = p_student_id AND subject_id = p_subject_id
               AND semester_id = p_semester_id AND status = 'APPROVED'
               AND score_type IN ('TX1','TX2','TX3','TX4');
            SELECT value INTO v_gk FROM scores
             WHERE student_id = p_student_id AND subject_id = p_subject_id
               AND semester_id = p_semester_id AND score_type = 'GK' AND status = 'APPROVED';
            SELECT value INTO v_ck FROM scores
             WHERE student_id = p_student_id AND subject_id = p_subject_id
               AND semester_id = p_semester_id AND score_type = 'CK' AND status = 'APPROVED';
            IF v_gk IS NULL OR v_ck IS NULL OR v_tx_count = 0 THEN
                RETURN NULL;
            END IF;
            RETURN ROUND((v_tx_sum + 2 * v_gk + 3 * v_ck) / (v_tx_count + 5), 2);
        END;
        $$ LANGUAGE plpgsql;
        """
    )

    # --- Measurement layer: độ khó thực nghiệm + điểm chuẩn hóa ---
    op.execute(
        """
        CREATE MATERIALIZED VIEW mv_exam_difficulty AS
        SELECT s.subject_id, s.semester_id, s.score_type, c.grade_id,
               COUNT(*) AS n,
               ROUND(AVG(s.value), 2) AS mean_score,
               ROUND(COALESCE(STDDEV_SAMP(s.value), 0), 2) AS stddev_score,
               ROUND(AVG((s.value < 5.0)::int)::numeric, 4) AS pct_below_5,
               ROUND(AVG(s.value) / 10.0, 4) AS facility_index
        FROM scores s
        JOIN classes c ON c.id = s.class_id
        WHERE s.status = 'APPROVED' AND s.score_type IN ('GK', 'CK')
        GROUP BY s.subject_id, s.semester_id, s.score_type, c.grade_id;
        """
    )
    op.execute(
        "CREATE UNIQUE INDEX idx_mv_diff ON mv_exam_difficulty"
        "(subject_id, semester_id, score_type, grade_id)"
    )
    op.execute(
        """
        CREATE VIEW v_normalized_scores AS
        SELECT s.id AS score_id, s.student_id, s.subject_id, s.semester_id,
               s.class_id, c.grade_id, s.score_type, s.value AS raw_value,
               d.mean_score, d.stddev_score, d.facility_index,
               CASE WHEN d.stddev_score > 0
                    THEN ROUND((s.value - d.mean_score) / d.stddev_score, 2)
                    ELSE 0 END AS z_score,
               CASE WHEN d.stddev_score > 0
                    THEN GREATEST(0, LEAST(10,
                         ROUND(7.0 + (s.value - d.mean_score) / d.stddev_score * 1.5, 2)))
                    ELSE s.value END AS context_adjusted_value
        FROM scores s
        JOIN classes c ON c.id = s.class_id
        JOIN mv_exam_difficulty d
          ON d.subject_id = s.subject_id AND d.semester_id = s.semester_id
         AND d.score_type = s.score_type AND d.grade_id = c.grade_id
        WHERE s.status = 'APPROVED' AND s.score_type IN ('GK', 'CK');
        """
    )

    # --- Seed: trường mặc định ---
    op.execute(
        """
        INSERT INTO schools (id, name, code, address)
        VALUES ('00000000-0000-0000-0000-000000000001', 'Trường THCS Mẫu',
                'THCS-MAU', '123 Đường ABC, Quận 1, TP.HCM');
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # --- Gỡ view/function trước (phụ thuộc vào bảng) ---
    op.execute("DROP VIEW IF EXISTS v_normalized_scores")
    op.execute("DROP MATERIALIZED VIEW IF EXISTS mv_exam_difficulty")
    op.execute("DROP FUNCTION IF EXISTS calc_subject_average(uuid, uuid, uuid)")
    op.execute("DROP FUNCTION IF EXISTS audit_scores_change() CASCADE")
    op.execute("DROP FUNCTION IF EXISTS update_updated_at() CASCADE")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_scores_type', table_name='scores')
    op.drop_index('idx_scores_subject', table_name='scores')
    op.drop_index('idx_scores_student', table_name='scores')
    op.drop_index('idx_scores_status', table_name='scores')
    op.drop_index('idx_scores_semester', table_name='scores')
    op.drop_index('idx_scores_exam', table_name='scores')
    op.drop_index('idx_scores_compound', table_name='scores')
    op.drop_index('idx_scores_class', table_name='scores')
    op.drop_table('scores')
    op.drop_index('idx_examcomp_unit', table_name='exam_competencies')
    op.drop_table('exam_competencies')
    op.drop_index('idx_ta_year', table_name='teacher_assignments')
    op.drop_index('idx_ta_user', table_name='teacher_assignments')
    op.drop_index('idx_ta_subject', table_name='teacher_assignments')
    op.drop_index('idx_ta_grade', table_name='teacher_assignments')
    op.drop_index('idx_ta_class', table_name='teacher_assignments')
    op.drop_table('teacher_assignments')
    op.drop_index('idx_exam_type', table_name='exam_papers')
    op.drop_index('idx_exam_subject', table_name='exam_papers')
    op.drop_index('idx_exam_semester', table_name='exam_papers')
    op.drop_index('idx_exam_grade', table_name='exam_papers')
    op.drop_table('exam_papers')
    op.drop_index('idx_enroll_year', table_name='enrollments')
    op.drop_index('idx_enroll_student', table_name='enrollments')
    op.drop_index('idx_enroll_class', table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index('idx_curri_subject', table_name='curriculum_units')
    op.drop_index('idx_curri_parent', table_name='curriculum_units')
    op.drop_table('curriculum_units')
    op.drop_index('idx_message_session', table_name='ai_messages')
    op.drop_table('ai_messages')
    op.drop_table('subjects')
    op.drop_table('semesters')
    op.drop_table('report_schedules')
    op.drop_table('refresh_tokens')
    op.drop_index('idx_classes_year', table_name='classes')
    op.drop_index('idx_classes_grade', table_name='classes')
    op.drop_table('classes')
    op.drop_index('idx_audit_user', table_name='audit_logs')
    op.drop_index('idx_audit_time', table_name='audit_logs')
    op.drop_index('idx_audit_table', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('idx_session_user', table_name='ai_sessions')
    op.drop_table('ai_sessions')
    op.drop_index('idx_users_school', table_name='users')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_students_name', table_name='students', postgresql_using='gin', postgresql_ops={'full_name': 'gin_trgm_ops'})
    op.drop_table('students')
    op.drop_table('grades')
    op.drop_table('academic_years')
    op.drop_table('schools')
    # ### end Alembic commands ###

    # --- Gỡ enum types ---
    for enum_name in (
        "guardrail_status_enum", "ai_session_role_enum", "difficulty_enum", "file_type_enum",
        "score_status_enum", "score_type_enum", "role_context_enum", "user_role_enum",
        "school_level_enum",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
