"""add classroom recordings

Revision ID: 61cd54a7a8ea
Revises: fbc889a3492b
Create Date: 2026-07-01 23:01:22.254150

"""
"""add classroom recordings

Revision ID: 61cd54a7a8ea
Revises: fbc889a3492b
Create Date: 2026-07-01 23:01:22.254150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61cd54a7a8ea'
down_revision: Union[str, Sequence[str], None] = 'fbc889a3492b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Enum types
recording_rank_enum = postgresql.ENUM('EXCELLENT', 'SATISFACTORY', 'NEEDS_IMPROVEMENT', name='recording_rank_enum', create_type=False)


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    recording_rank_enum.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classroom_recordings',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('semester_id', sa.UUID(), nullable=False),
    sa.Column('lesson_name', sa.String(length=255), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('audio_file_url', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('progress', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('engagement', sa.String(length=20), nullable=True),
    sa.Column('rank', recording_rank_enum, nullable=True),
    sa.Column('ai_report', sa.Text(), nullable=True),
    sa.Column('transcript', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_classroom_recordings_class_id_classes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_classroom_recordings_school_id_schools'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], name=op.f('fk_classroom_recordings_semester_id_semesters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_classroom_recordings_subject_id_subjects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('fk_classroom_recordings_teacher_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_classroom_recordings'))
    )
    op.create_index('idx_recordings_class', 'classroom_recordings', ['class_id'], unique=False)
    op.create_index('idx_recordings_school', 'classroom_recordings', ['school_id'], unique=False)
    op.create_index('idx_recordings_subject', 'classroom_recordings', ['subject_id'], unique=False)
    op.create_index('idx_recordings_teacher', 'classroom_recordings', ['teacher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_recordings_teacher', table_name='classroom_recordings')
    op.drop_index('idx_recordings_subject', table_name='classroom_recordings')
    op.drop_index('idx_recordings_school', table_name='classroom_recordings')
    op.drop_index('idx_recordings_class', table_name='classroom_recordings')
    op.drop_table('classroom_recordings')
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS recording_rank_enum")
