"""add_feedback_and_telemetry_to_ai_messages

Revision ID: 685efdc5b749
Revises: d3a6f0a9c1b7
Create Date: 2026-06-28 02:19:44.744615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '685efdc5b749'
down_revision: Union[str, Sequence[str], None] = 'd3a6f0a9c1b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_messages', sa.Column('rating', sa.SmallInteger(), nullable=True))
    op.add_column('ai_messages', sa.Column('feedback_text', sa.Text(), nullable=True))
    op.add_column('ai_messages', sa.Column('feedback_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ai_messages', sa.Column('thought_trace', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('ai_messages', sa.Column('input_token_count', sa.Integer(), nullable=True))
    op.add_column('ai_messages', sa.Column('output_token_count', sa.Integer(), nullable=True))
    op.add_column('ai_messages', sa.Column('cost', sa.Numeric(precision=10, scale=6), nullable=True))
    op.add_column('ai_messages', sa.Column('llm_provider', sa.String(length=50), nullable=True))
    
    # Ràng buộc rating chỉ được phép là 1 hoặc -1
    op.create_check_constraint(
        'chk_aimessage_rating',
        'ai_messages',
        'rating IN (1, -1)'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chk_aimessage_rating', 'ai_messages', type_='check')
    op.drop_column('ai_messages', 'llm_provider')
    op.drop_column('ai_messages', 'cost')
    op.drop_column('ai_messages', 'output_token_count')
    op.drop_column('ai_messages', 'input_token_count')
    op.drop_column('ai_messages', 'thought_trace')
    op.drop_column('ai_messages', 'feedback_at')
    op.drop_column('ai_messages', 'feedback_text')
    op.drop_column('ai_messages', 'rating')
    # ### end Alembic commands ###
