"""misconceptions table + GENERATION_FAILED notification type

Revision ID: 8180b7030cd6
Revises: 61cd54a7a8ea
Create Date: 2026-07-04 05:17:10.630526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8180b7030cd6'
down_revision: Union[str, Sequence[str], None] = '61cd54a7a8ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Autogenerate không tự phát hiện giá trị enum mới thêm vào NotificationType.
    op.execute("ALTER TYPE notification_type_enum ADD VALUE IF NOT EXISTS 'GENERATION_FAILED'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('misconceptions',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=True),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('grade_number', sa.SmallInteger(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('example_wrong', sa.Text(), nullable=True),
    sa.Column('evidence_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_misconceptions_school_id_schools'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_misconceptions_subject_id_subjects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['curriculum_units.id'], name=op.f('fk_misconceptions_unit_id_curriculum_units'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_misconceptions'))
    )
    op.create_index('idx_misconception_unit', 'misconceptions', ['unit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_misconception_unit', table_name='misconceptions')
    op.drop_table('misconceptions')
    # ### end Alembic commands ###
    # enum value không xóa được, giữ nguyên
