"""add subject_id (mon phu trach) to users

Revision ID: c5add4571b15
Revises: 22c8055463af
Create Date: 2026-06-14 16:25:33.331989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5add4571b15'
down_revision: Union[str, Sequence[str], None] = '22c8055463af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subject_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_users_subject_id_subjects'), 'users', 'subjects', ['subject_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_subject_id_subjects'), 'users', type_='foreignkey')
    op.drop_column('users', 'subject_id')
    # ### end Alembic commands ###
