"""add_feedback_tag_to_ai_messages

Revision ID: dfd758473722
Revises: 685efdc5b749
Create Date: 2026-06-28 02:41:21.182848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfd758473722'
down_revision: Union[str, Sequence[str], None] = '685efdc5b749'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_messages', sa.Column('feedback_tag', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_messages', 'feedback_tag')
    # ### end Alembic commands ###
