"""add agent_routes and agent_step_p95_ms to ai_observability_snapshots

Revision ID: fbc889a3492b
Revises: 7e041ad02d53
Create Date: 2026-07-01 01:28:02.406460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fbc889a3492b'
down_revision: Union[str, Sequence[str], None] = '7e041ad02d53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_observability_snapshots', sa.Column('agent_routes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.add_column('ai_observability_snapshots', sa.Column('agent_step_p95_ms', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_observability_snapshots', 'agent_step_p95_ms')
    op.drop_column('ai_observability_snapshots', 'agent_routes')
    # ### end Alembic commands ###
